package comm;

/**
 *
 * @author luka
 */
public enum Operation {
    PING,
    LOGIN,
    REGISTER,
    ACTIVITY_GET,
    ACTIVITY_NEW,
    ACTIVITY_UPDATE,
    ACTIVITY_DELETE,
    ATHLETE_GET,
    ATHLETE_NEW,
    ATHLETE_UPDATE,
    ATHLETE_DELETE,
    CLUB_GET,
    CLUB_GET_BY_ID,
    CLUB_NEW,
    CLUB_UPDATE,
    CLUB_DELETE,
    ER_GET,
    ER_NEW,
    ER_START,
    ER_END,
    EVALUATION_GET,
    EVALUATION_NEW,
    EVALUATION_UPDATE,
    EVALUATION_DELETE,
    EVALUATOR_GET,
    EVALUATOR_UPDATE,
    EVALUATOR_DELETE,
    EVALUATOR_GET_ROLES,
    ROLE_GET,
    ROLE_NEW,
    ROLE_UPDATE,
    ROLE_DELETE
}
