package ui;

import ui.evaluator.PanelEvaluator;
import audit.Audit;
import client.Client;
import java.awt.Container;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JPanel;
import ui.athlete.PanelAthlete;

/**
 *
 * @author luka
 */
public class FormMain extends javax.swing.JFrame {

    /**
     * Creates new form FormMain
     */
    public FormMain() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setTitle(Audit.getLoggedUser().toString());
        
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                Client.endConnection();
            }
        });
    }
    
    private void swapPanel(JPanel panel) {
        Container contentPane = this.getContentPane();
        contentPane.removeAll();
        contentPane.add(panel);
        contentPane.revalidate();
        contentPane.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnEvaluation = new javax.swing.JMenu();
        mnAthlete = new javax.swing.JMenu();
        mnEvaluator = new javax.swing.JMenu();
        mnClub = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        mnSettings = new javax.swing.JMenu();
        mnInfo = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnEvaluation.setText("Kontrole");
        jMenuBar1.add(mnEvaluation);

        mnAthlete.setText("Takmičari");
        mnAthlete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnAthleteMouseClicked(evt);
            }
        });
        mnAthlete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAthleteActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnAthlete);

        mnEvaluator.setText("Ocenjivači");
        mnEvaluator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnEvaluatorMouseClicked(evt);
            }
        });
        mnEvaluator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEvaluatorActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnEvaluator);

        mnClub.setText("Klubovi");
        jMenuBar1.add(mnClub);

        jMenu7.setText("Šifrarnici");
        jMenuBar1.add(jMenu7);

        mnSettings.setText("Podešavanja");
        jMenuBar1.add(mnSettings);

        mnInfo.setText("O programu");
        jMenuBar1.add(mnInfo);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnEvaluatorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnEvaluatorMouseClicked
        swapPanel(new PanelEvaluator());
    }//GEN-LAST:event_mnEvaluatorMouseClicked

    private void mnEvaluatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEvaluatorActionPerformed
        
    }//GEN-LAST:event_mnEvaluatorActionPerformed

    private void mnAthleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAthleteActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_mnAthleteActionPerformed

    private void mnAthleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnAthleteMouseClicked
         swapPanel(new PanelAthlete());   
    }//GEN-LAST:event_mnAthleteMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu mnAthlete;
    private javax.swing.JMenu mnClub;
    private javax.swing.JMenu mnEvaluation;
    private javax.swing.JMenu mnEvaluator;
    private javax.swing.JMenu mnInfo;
    private javax.swing.JMenu mnSettings;
    // End of variables declaration//GEN-END:variables
}
